[settings]
port = 8888
station = "Z0000"
output_dir = "rsudp"
debug = true

[printdata]
enabled = false

[write]
enabled = false
channels = ["all"]

[plot]
enabled = true
duration = 90
refresh_interval = 0
spectrogram = true
fullscreen = false
kiosk = false
eq_screenshots = false
channels = ["all"]
filter_waveform = false
filter_spectrogram = false
filter_highpass = 0.7
filter_lowpass = 2.0
filter_corners = 4
spectrogram_freq_range = false
upper_limit = 15.0
lower_limit = 0.0
logarithmic_y_axis = false
deconvolve = true
units = "CHAN"

[forward]
enabled = false
address = ["192.168.1.254"]
port = [8888]
channels = ["all"]
fwd_data = true
fwd_alarms = false

[alert]
enabled = true
channel = "HZ"
sta = 6.0
lta = 30.0
duration = 0.0
threshold = 1.1
reset = 0.5
highpass = 0.1
lowpass = 2.0
deconvolve = false
units = "VEL"
on_plot = false
on_plot_end_line_color = "#D72638"
on_plot_start_line_color = "#4C8BF5"

[alertsound]
enabled = false
mp3file = "doorbell"

[custom]
enabled = false
codefile = "n/a"
win_override = false

[tweets]
enabled = false
tweet_images = true
api_key = "n/a"
api_secret = "n/a"
access_token = "n/a"
access_secret = "n/a"
extra_text = ""

[telegram]
enabled = false
send_images = true
token = "n/a"
chat_id = "n/a"
extra_text = ""
upload_timeout = 10

[googlechat]
enabled = false
webhook_url = "n/a"
extra_text = ""
send_images = false
s3_object_key_prefix = "rsudp/googlechat/"
s3_upload_timeout_seconds = 3

[discord]
enabled = false
webhook_url = "n/a"
use_embed = true
send_images = true
extra_text = ""

[sns]
enabled = false
topic_arn = "n/a"
aws_region = "n/a"
extra_text = ""

[line]
enabled = false
channel_access_token = "n/a"
to_ids = ""
extra_text = ""
send_images = true
s3_object_key_prefix = "rsudp/line/"
s3_upload_timeout_seconds = 3

[bluesky]
enabled = false
post_images = true
username = "n/a"
password = "n/a"
extra_text = ""

[rsam]
enabled = false
quiet = true
fwaddr = "192.168.1.254"
fwport = 8887
fwformat = "LITE"
channel = "HZ"
interval = 10
deconvolve = false
units = "VEL"

[hue]
enabled = false
app_key = ""
target_ids = []
