[settings]
port = 10101
station = "R6E01"
output_dir = "rsudp"
debug = true

[alert]
enabled = true
channel = "HZ"
sta = 6.0
lta = 30.0
duration = 0.0
threshold = 1.1
reset = 0.5
highpass = 0.1
lowpass = 2.0
deconvolve = false
units = "counts"
on_plot = false

[plot]
enabled = false 
duration = 300
spectrogram = false
fullscreen = false
kiosk = false
